-- Run this in Supabase SQL Editor.
-- It creates tables + inserts your Phase 1 service data.

create table if not exists public.service_category (
  id bigint primary key,
  title_en text not null,
  title_ms text not null,
  icon_key text not null,
  sort_order int not null default 0
);

create table if not exists public.service_item (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.service_category(id) on delete cascade,
  label text not null,
  sort_order int not null default 0
);

create index if not exists idx_service_item_category on public.service_item(category_id);

-- Allow read-only access for anon key (Phase 1 view-only).
alter table public.service_category enable row level security;
alter table public.service_item enable row level security;

drop policy if exists "public read service_category" on public.service_category;
create policy "public read service_category"
on public.service_category
for select
to anon
using (true);

drop policy if exists "public read service_item" on public.service_item;
create policy "public read service_item"
on public.service_item
for select
to anon
using (true);

-- Seed (id values match your UI)
insert into public.service_category (id, title_en, title_ms, icon_key, sort_order) values
  (1,  'Aids / Bantuan for student', 'Bantuan Pelajar',          'GraduationCap', 1),
  (2,  'Biasiswa',                  'Scholarships',             'BookOpen',      2),
  (3,  'Pinjaman',                  'Loans',                   'Calculator',    3),
  (4,  'Program dan bantuan',       'Programs & Aid',          'Heart',         4),
  (6,  'Bayaran balik pinjaman',    'Loan Repayment',          'FileText',      6),
  (7,  'Hantar Keputusan / Laporan','Submit Results',          'FileText',      7),
  (8,  'Business Trade',            'Perdagangan Bisnes',      'Briefcase',     8),
  (9,  'Council Service',           'Perkhidmatan Majlis',     'Building2',     9),
  (10, 'Education & Learning',      'Pendidikan & Pembelajaran','GraduationCap',10),
  (11, 'Hydrology',                 'Hidrologi',               'Droplets',      11),
  (12, 'Land & Agriculture',        'Tanah & Pertanian',       'Map',           12),
  (13, 'Licence & Permit',          'Lesen & Permit',          'FileText',      13),
  (14, 'Life Event',                'Acara Kehidupan',         'Heart',         14),
  (15, 'Social & Community',        'Sosial & Komuniti',       'Landmark',      15),
  (16, 'Utilities',                 'Utiliti',                 'UtilityPole',   16)
on conflict (id) do update set
  title_en = excluded.title_en,
  title_ms = excluded.title_ms,
  icon_key = excluded.icon_key,
  sort_order = excluded.sort_order;

-- Clear items then re-insert (simple reseed)
delete from public.service_item;

insert into public.service_item (category_id, label, sort_order) values
  (1,'Bantuan kewangan khas',1),(1,'Laptop',2),(1,'Book',3),(1,'Free school transport',4),(1,'School scholarship',5),(1,'Tuition',6),(1,'Uniform',7),
  (2,'Biasiswa yayasan sarawak tun taib',1),(2,'Yayasan biasiswa Sarawak tunku Abdul rahman (YBSTAR)',2),(2,'Biasiswa khas program perubatan unias',3),(2,'Biasiswa tempatan yayasan sarawak',4),(2,'Bantuan kemasukan ke IPT',5),(2,'Bursari BP40',6),(2,'Inisiatif Graduan Pulang Sarawak (i - GPS)',7),
  (3,'Biasiswa pinjaman pelajaran dalam negara',1),(3,'Pinjaman pelajaran luar negara',2),(3,'Biasiswa pinjaman latihan teknikal',3),
  (4,'Biasiswa program pertukaran pelajaran',1),(4,'Program pendidikan komuniti',2),(4,'Program bantuan pakaian seragam sekolah',3),(4,'Program HiPERS',4),(4,'Perkhidmatan pengangkutan percuma',5),(4,'Program tuisyen sekolah menengah',6),(4,'Anugerah khas premier sarawak (AKPS)',7),(4,'Program pemerkasaan Bahasa inggeris (EPP)',8),(4,'Anugerah Graduan Cemerlang',9),(4,'YS-JPNS Collaborations Programs',10),
  (6,'Kaedah Pembayaran',1),(6,'Insentif Pembayaran',2),
  (7,'Form Penghantaran Keputusan Semester',1),(7,'Laporan Prestasi Pengajian',2),
  (8,'Application for permit to operate (telecommunications)',1),(8,'Application for rooftop structure & in-building system',2),(8,'Application for WayLeave',3),(8,'Application to become panel hotel',4),(8,'Application to become panel travel agent',5),(8,'Apply for manufacturing permit',6),(8,'eProcurement (Contractor & Supplier)',7),(8,'Register with UPKJ',8),(8,'Sarawak Micro Credit Scheme (SMCS)',9),(8,'Sitting application for telecommunication tower',10),(8,'Quotation and Tender Notices',11),
  (9,'Certificate of clearance of indebtedness',1),(9,'Transfer of ownership of rateable holdings',2),(9,'Withdrawal of caveat',3),(9,'e-billing of assessment rates',4),(9,'House numbering and referencing',5),(9,'Payment of assessment rates by installment',6),(9,'Rebate of assessment rates',7),(9,'Remission of rates',8),(9,'Update owner information',9),
  (10,'Apply for scholarships (State Govt)',1),(10,'Purchase Sarawak hydrological year book',2),(10,'Online request of hydrological data',3),(10,'School leavers registration (SPEAK)',4),(10,'Search of statues of Sarawak',5),(10,'1 village 1 story photos',6),(10,'Update school profile',7),
  (11,'Purchase Sarawak hydrological year book (individual)',1),(11,'Purchase Sarawak hydrological year book (organization)',2),(11,'Online request of hydrological data (government agency/semi government agency)',3),(11,'Online request of hydrological data (individuals)',4),(11,'Online request of hydrological data (IPTA/IPTS)',5),(11,'Online request of hydrological data (private agency/organization)',6),
  (12,'Permission to deal',1),(12,'Rice and maize development',2),(12,'Inland fisheries assistance',3),(12,'Plantation crop division assistance',4),(12,'Certificate of crop scheme',5),(12,'SPBT Authentication',6),(12,'Exchange of farm ownership',7),(12,'TOL residential renewal',8),(12,'Rock materials sales outside Sarawak',9),(12,'TKPM Application',10),
  (13,'Change of Permanent Specialist',1),(13,'EIA Consultant Registration',2),(13,'SPA Qualified Person Renewal',3),(13,'Carbon Storage Licence',4),(13,'Switchboard Manufacturer Registration',5),(13,'Water Supply Products Certification',6),(13,'Endorsement of Wireman',7),
  (14,'Adat Marriage Pre-Registration',1),(14,'Senior Citizen Health Benefit (SCHB)',2),(14,'Apply Job with State Government',3),(14,'Kenyalang Gold Card (KGC) Status',4),(14,'Islamic Religious Enquiry',5),(14,'Native Court Case Status',6),(14,'Pre Marriage Course',7),(14,'Faraq Nikah / Iddah Requests',8),(14,'Tuntutan Fasakh / Harta Sepencarian',9),
  (15,'Activate KGC',1),(15,'Museum Tickets',2),(15,'National Park Tickets',3),(15,'Bantuan Ibu Bersalin (BIB)',4),(15,'Bantuan Ihsan Kematian (BIK)',5),(15,'Endowment Fund Sarawak (EFS)',6),(15,'NGO Empowerment Grant',7),(15,'Recognized as Sarawak Natives',8),
  (16,'Gas Piping Installation (ATI/ATO)',1),(16,'Gas Competency Certificate',2),(16,'New Water Supply Connection',3),(16,'Water Bill Installments',4),(16,'Rural Electrification (BELB)',5),(16,'Lampu Jalan Kampung (LJK)',6),(16,'Pipe Fitter License',7);

